version: '3.7'

# Services/Containers to orchestrate in this composition
services:
  # Basic PHP 7.4 & Apache2 Image Container
  php-7-4-web-server:
    container_name: php-7-4-web-server
    tty: true
    restart: unless-stopped
    build: 
      context: .
      target: php-7-4-build
      dockerfile: php-7-4-apache.Dockerfile
      args:
        - APP_ENV=${APP_ENV}
      labels:
        ewc.name: "Web Server"
        ewc.description: "PHP & Apache Web Server"
        ewc.php.version: "7.4"
        ewc.label-with-empty-value: ""
    image: php-7-4-web-server:latest
    environment:
        - APP_ENV=${APP_ENV}
        - APP_PORT=${APP_PORT}
        - APP_PORT_SSL=${APP_PORT_SSL}
    working_dir: /var/www
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_SSL}:443
    volumes:
      - ./public_html:/var/www/html
      - ./docker-files/php/local.ini:/usr/local/etc/php.ini
    networks:
      - webapp_network

# Custom network for composed containers to communicate on
networks:
  webapp_network:
    driver: bridge

